CREATE DATABASE urlshortener;

CREATE TABLE url_shorteners
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    destination_url VARCHAR(255),
    url_slug        VARCHAR(255),
    expire_at       TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_url_shorteners PRIMARY KEY (id)
);

ALTER TABLE url_shorteners
    ADD CONSTRAINT uc_url_shorteners_urlslug UNIQUE (url_slug);